server:
  port: 8081
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
      - id: farmer-service
        uri: http://localhost:8080
        predicates:
        - Path=/farmers/**
      - id: dealer-service
        uri: http://localhost:8083
        predicates:
        - Path=/dealer/**
      - id: admin-service
        uri: http://localhost:8089
        predicates:
        - Path=/aadmin/**
      - id: paymentservice
        uri: http://localhost:8085
        predicates:
        - Path=/payments/**
eureka:
  instance:
    hostname: localhost
  